spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jdbctemplent
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver



# 配置mybatis规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置 这个可以省略
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
